# Generated by Django 2.2.7 on 2020-01-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20200126_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
