# Generated by Django 2.2.7 on 2020-01-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
