# Generated by Django 2.2.7 on 2020-01-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
