# Generated by Django 2.2.7 on 2020-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('X', 'No size selected'), ('4', 'Size 4'), ('6', 'Size 6'), ('8', 'Size 8'), ('10', 'Size 10'), ('12', 'Size 12'), ('14', 'Size 14'), ('16', 'Size 16')], default='X', max_length=1, null=True),
        ),
    ]
