# Generated by Django 2.2.7 on 2020-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('X', 'Select colour'), ('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Different', 'Different')], default='X', max_length=1, null=True),
        ),
    ]
