# Generated by Django 2.2.7 on 2020-01-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
