# Generated by Django 2.2.7 on 2020-02-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200202_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='productpictures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shop.Product'),
        ),
    ]
